spring:

  datasource:
    url: jdbc:mysql://localhost:3306/listing_app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  jooq:
    sql-dialect: MySQLDialect

server:
  port: 8090

